
services:
  trader-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: 
      - .env
    container_name: trader-dev
    volumes:
      - ./src:/app/src
    ports:
      - "8888:8888"
    restart: unless-stopped

  trader-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file: 
      - .env
    container_name: trader-prod
    # In production, you may not need volume mapping since the code is baked into the image.
    ports:
      - "8000:8000"
    restart: unless-stopped



