


services:
  trader:
    build: .
    container_name: trader
    volumes:
      - ./src/backtesting:/app/src/backtesting
      - ./src/production:/app/src/production
    
    restart: unless-stopped


