
services:
  trader:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: trader-dev
    volumes:
      - ./src:/app/src
    ports:
      - "8888:8888"
    restart: unless-stopped

  



